web:
  replicaCount: 1
  image:
    repository: baiyuliu/server-web
    tag: latest
    pullPolicy: IfNotPresent
  env:
    MYSQL_HOST: database-service
    MYSQL_DATABASE: lookup_db
    MYSQL_USER: username
    MYSQL_PASSWORD:
          name: mysql-credentials
          key: password

  service:
    name: web-service
    type: NodePort
    port: 3000
    targetPort: 3000


database:
  replicaCount: 1
  image:
    repository: baiyuliu/mysql-service
    tag: latest
    pullPolicy: IfNotPresent
  ports:
    - containerPort: 3306
  volumes:
    - name: database-storage
      emptyDir: {}


  service:
    name: database-service
    port: 3306
    targetPort: 3306
