version: '3'

services:
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lookup_db
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    networks:
      - my-network
    hostname: database-service

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - my-network
    hostname: web-service

networks:
  my-network:
