apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: {{ .Values.web.env.MYSQL_HOST }}
            - name: MYSQL_DATABASE
              value: {{ .Values.web.env.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.web.env.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.web.env.MYSQL_PASSWORD.valueFrom.secretKeyRef.name }}
                  key: {{ .Values.web.env.MYSQL_PASSWORD.valueFrom.secretKeyRef.key }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.service.name }}
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
  type: {{ .Values.web.service.type }}
