CREATE DATABASE IF NOT EXISTS lookup_db;
CREATE USER IF NOT EXISTS 'username'@'%' IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON lookup_db.* TO 'username'@'%';
FLUSH PRIVILEGES;


USE lookup_db;

CREATE TABLE IF NOT EXISTS lookup_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  domain VARCHAR(255) NOT NULL,
  result TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

