name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push web image
        run: |
          docker build -t server-web:latest -f web.Dockerfile .
          docker tag server-web:latest baiyuliu/server-web:latest
          docker push baiyuliu/server-web:latest

      - name: Set up MySQL credentials
        env:
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          echo "CREATE DATABASE IF NOT EXISTS lookup_db;
          CREATE USER IF NOT EXISTS '${MYSQL_USERNAME}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';

          GRANT ALL PRIVILEGES ON lookup_db.* TO '${MYSQL_USERNAME}'@'%';
          FLUSH PRIVILEGES;

          USE lookup_db;

          CREATE TABLE IF NOT EXISTS lookup_logs (
            id INT AUTO_INCREMENT PRIMARY KEY,
            domain VARCHAR(255) NOT NULL,
            result TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          ) ENGINE=InnoDB;" > init.sq

      - name: Build and push database image
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          #docker build -t baiyuliu/mysql-service:latest --build-arg MYSQL_PASSWORD=${MYSQL_PASSWORD}  -f database.Dockerfile .
          docker build -t mysql-service:latest -f database.Dockerfile .
          docker tag mysql-service:latest baiyuliu/mysql-service:latest
          docker push baiyuliu/mysql-service:latest


      - name: Set up MySQL password
        run: |
          echo "mysql:" >> values.yaml
          echo "  password: ${{ secrets.MYSQL_PASSWORD }}" >> values.yaml


      - name: Deploy Helm chart
        run: helm install my-release mychart
