name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t server-web:latest -f web.Dockerfile .
          docker tag server-web:latest baiyuliu/server-web:latest
          docker push baiyuliu/server-web:latest

      - name: Deploy using Helm
        run: helm install my-release mychart
